name: openra
version: '20170527'
summary: A Libre/Free Real Time Strategy game engine supporting early Westwood classics
description: |
  Open Source real-time strategy game engine for early Westwood games
  such as Command & Conquer: Red Alert written in C# using SDL and
  OpenGL. Runs on Windows, Linux, *BSD and Mac OS X.
icon: icons/openra-ra.svg
confinement: strict

apps:
  openra:
    command: desktop-launch $SNAP/usr/bin/mono-sgen $SNAP/usr/local/lib/openra/OpenRA.Game.exe
    environment:
      MONO_CFG_DIR: $SNAP/etc
      MONO_CONFIG: $SNAP/etc/mono/config
      MONO_GAC_PREFIX: $SNAP/usr/lib/mono
    plugs:
      - mount-observe
      - network
      - network-bind
      - opengl
      - optical-drive
      - pulseaudio
      - unity7
      - x11

parts:
  openra:
    plugin: make
    source: https://github.com/OpenRA/OpenRA/archive/release-20170527.tar.gz
    prepare: |
      make dependencies
    install: |
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install-linux-shortcuts
    after: [desktop-glib-only]
    build-packages:
      - curl
      - libfreetype6-dev
      - liblua5.1-0-dev
      - libopenal-dev
      - libsdl2-dev
      - mono-devel
      - nuget
      - unzip
    stage-packages:
      - libfreetype6
      - liblua5.1-0
      - libopenal1
      - libsdl2-2.0-0
      - mono-complete
